# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ad11ddf60186ff1ad62f66dcc1cb6769097ebf7fb22cdb7e9dce5dbc6c74caf51056d801461f73c68aa1691fcbac8ffa55628f820933f1ca8eb621e7de985c7

test:
  secret_key_base: 8e74f850402123068bd0a3cdf703ad1314cf84aa488a0d97b78d314ca9eba0813ab80eae9eb490d30751f338622f89359aebd99f43375b5dd9da7239bafcda8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
